# Development critics initialization
from fitdev.critics.development.frontend_critic import FrontendDeveloperCritic
from fitdev.critics.development.backend_critic import BackendDeveloperCritic
from fitdev.critics.development.fullstack_critic import FullStackDeveloperCritic
from fitdev.critics.development.devops_critic import DevOpsEngineerCritic
